# Generated by Django 4.2.19 on 2025-02-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_title', models.CharField(blank=True, max_length=200, null=True)),
                ('certificate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
