# Generated by Django 4.2.19 on 2025-02-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifucates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_title',
        ),
    ]
