# Generated by Django 4.2.19 on 2025-02-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifucates', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
