# Generated by Django 4.2.19 on 2025-02-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifucates', '0005_certificate_image_url_certificate_issued_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='image_url',
        ),
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
