# Generated by Django 4.2.19 on 2025-02-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_title', models.CharField(max_length=100)),
                ('About_p', models.TextField()),
                ('About_Linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('About_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('About_City', models.CharField(blank=True, max_length=100, null=True)),
                ('About_Country', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='Portfolio_images/')),
            ],
        ),
    ]
