# Generated by Django 4.2.19 on 2025-02-18 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_skills_remove_education_skill_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
