# Generated by Django 4.2.19 on 2025-02-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0003_delete_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_image', models.ImageField(blank=True, null=True, upload_to='Portfolio_image/')),
            ],
        ),
    ]
