# Generated by Django 4.2.19 on 2025-02-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=200, null=True)),
                ('project_name1', models.CharField(blank=True, max_length=255, null=True)),
                ('project_description1', models.TextField(blank=True, null=True)),
                ('project_image1', models.ImageField(blank=True, null=True, upload_to='Portfolio_images/')),
                ('project_image2', models.ImageField(blank=True, null=True, upload_to='Portfolio_images/')),
                ('project_image3', models.ImageField(blank=True, null=True, upload_to='Portfolio_images/')),
                ('project_image4', models.ImageField(blank=True, null=True, upload_to='Portfolio_images/')),
                ('project_image5', models.ImageField(blank=True, null=True, upload_to='Portfolio_images/')),
                ('project_image6', models.ImageField(blank=True, null=True, upload_to='Portfolio_images/')),
            ],
        ),
    ]
