# Generated by Django 4.2.19 on 2025-02-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_title',
        ),
    ]
