# Generated by Django 4.2.19 on 2025-02-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_projects_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_image2',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_image3',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_image4',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_image5',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_image6',
        ),
    ]
